import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charset="UTF-8">
        <title>Wiselogix Technologies</title>

        <meta name="description" content="Wiselogix Technologies offers Web Development, App Development, Software Development and much more..." />

        <link href="/assets/images/favicon.ico" rel="favicon" type="image/x-icon" />
        <meta name='viewport' content='width=device-width, initial-scale=1.0'>
        <meta http-equiv='X-UA-Compatible' content='IE=edge'>

        <!-- Google Fonts -->
        <!-- <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=%3A400' media='all' /> -->

        <!-- CSS Files -->
        <link rel='stylesheet' href='assets/css/fontawesome.css' media='all'>
        <link rel='stylesheet' href='assets/css/ultimate-icons.css' media='all'>
        <link rel='stylesheet' href='assets/css/dashicons.min.css' media='all'>
        <link rel='stylesheet' href='assets/css/block-liberary.css' media='all'>
        <link rel='stylesheet' href='assets/css/jquery.magnificpopup.css' media='all'>
        <link rel='stylesheet' href='assets/css/bootstrap-3.4.1.css' media='all'>
        <link rel='stylesheet' href='assets/css/skin.css' media='all'>
        <link rel='stylesheet' href='assets/css/main.css' media='all'>
        <link rel='stylesheet' href='assets/css/bb-theme-responsive.css' media='all'>
        <link rel='stylesheet' href='assets/css/bb-theme-accessible.css' media='all'>
        <link rel='stylesheet' href='assets/css/slick/slick.css' media='all'>
        <link rel='stylesheet' href='assets/css/slick/slick-theme.css' media='all'>
        <link rel='stylesheet' href='assets/css/homepage.css' media='all'>
        <link rel='stylesheet' href='assets/css/homepage_responsive.css' media='all'>
        <link rel='stylesheet' href='assets/css/focus.css' media='all'>
        <link rel='stylesheet' href='assets/css/focus_responsive.css' media='all'>
        <link rel='stylesheet' href='assets/css/bb-loop.css' media='all'>
        <link rel='stylesheet' href='assets/css/bb-loop-responsive.css' media='all'>
        <link rel='stylesheet' href='assets/css/complianz-gdpr.css' media='all'>
        <link rel='stylesheet' href='assets/css/wp-blocks.css' media='all'>
        <link rel='stylesheet' href='assets/css/layout.css' media='all'>

        <!-- Custom CSS Files -->
        <link rel='stylesheet' href='assets/css/custom.css' media='all'>
        <link rel='stylesheet' href='assets/css/responsive.css' media='all'>

        <!-- JS Files -->
        <script src="assets/js/jquery.js"></script>
        <script src="assets/js/jquery-migrate.js"></script>
        <script src="assets/js/bb-loop.js"></script>
        <script src="assets/js/main.js"></script>
        <script src="assets/js/slick.js"></script>
        <script src="assets/js/isotope.js"></script>
        <script src="assets/js/imagesLoaded.js"></script>
        <script src="assets/js/filter.js"></script>
        <script src="assets/js/focus.js"></script>

        <!-- Custon JS Files -->
        <script src="assets/js/custom.js"></script>

      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <!--HEADER -->
        <header
          class="fl-page-header fl-page-header-primary fl-page-nav-centered-inline-logo fl-page-nav-toggle-button fl-page-nav-toggle-visible-mobile header_height_fix"
          itemscope="itemscope" itemtype="https://schema.org/WPHeader">
          <!-- .fl-page-bar2 -->
          <div class="fl-page-bar">
            <div class="fl-page-bar-container">
              <div class="top_bar_title">Ending global poverty begins with women’s rights</div>
              <nav class="top-bar-nav" aria-labelledby="quick-access" itemscope="itemscope"
                itemtype="https://schema.org/SiteNavigationElement">
                <h2 id="quick-access" class="sr-only">Quick Access</h2>
                <ul id="menu-top-menu" class="fl-page-bar-nav nav navbar-nav menu" aria-labelledby="quick-access">
                  <li id="menu-item-35"
                    class="topbar_join menu-item menu-item-type-custom menu-item-object-custom menu-item-35 nav-item">
                    <button class="nav-link">Sign Up</button>
                  </li><!--get rid of white space display in browsers
                          -->
                  <li id="menu-item-36"
                    class="menu-item menu-item-type-custom menu-item-object-custom menu-item-36 nav-item"><a
                      href="#" class="nav-link" target="_self">Shop Unwrapped</a>
                  </li><!--
                          -->
                  <li id="menu-item-29966"
                    class="topbar_search menu-item menu-item-type-custom menu-item-object-custom menu-item-29966 nav-item">
                    <button class="nav-link">Search</button>
                  </li>
                </ul>
              </nav>
            </div>
          </div>
          <!-- .fl-page-bar -->

          <!-- SEARCH BOX SLIDE DOWN -->
          <div class="searchbox" id="searchbox">
            <div class="search_wrap" role="dialog" aria-modal="true" aria-labelledby="search-modal-title">
              <div class="search_inner">
                <span class="modal-focus-trap" aria-hidden="true" id="search-top" tabindex="0"
                  data-target="search-close"></span>
                <h3 id="search-modal-title" class="sr-only">Search</h3>

                <form method="get" id="searchform" action="#">
                  <label for="search_input">What can we help you find?</label>
                  <input id="search_input" type="text" name="s" class="search_input">
                </form>
                <button class="search_button" form="searchform">Search</button>
                <button id="search-close" class="search_close" aria-label="Close"><i class="fas fa-times"
                    aria-hidden="true"></i></button>
                <span class="modal-focus-trap" aria-hidden="true" id="search-bottom" tabindex="0"
                  data-target="search"></span>
              </div>
            </div>
          </div>
          <!-- SEARCH BOX SLIDE DOWN -->

          <!-- SIGN UP FORM HEADER -->
          <div id="joinusbox" class="joinusbox header">
            <div class="joinus_wrap" role="dialog" aria-modal="true" aria-labelledby="joinusform-header-title">
              <div class="search_inner">

                <span class="modal-focus-trap" aria-hidden="true" id="joinus-top" tabindex="0"
                  data-target="joinus-close"></span>
                <h3 id="joinusform-header-title" class="sr-only">Sign up</h3>

                <form id="joinusform_header" method="get"
                  action="#"
                  class="en__component en__component--page joinus-form" target="_self">


                  <!-- first name -->
                  <div class="en__field en__field--text en__field--306158 en__field--firstName en__mandatory">
                    <div class="en__field__element en__field__element--text ">
                      <label for="en__field_supporter_firstName_inheader">First Name (required)</label>
                      <input autocomplete="given-name" id="en__field_supporter_firstName_inheader" required
                        aria-required="true" type="text"
                        class="join_input en__field__input en__field__input--text"
                        name="supporter.firstName" value="">
                    </div>
                  </div>

                  <!-- last name -->
                  <div class="en__field en__field--text en__field--306160 en__field--lastName en__mandatory">
                    <div class="en__field__element en__field__element--text">
                      <label for="en__field_supporter_lastName_inheader">Last Name (required)</label>
                      <input autocomplete="family-name" id="en__field_supporter_lastName_inheader" required
                        aria-required="true" type="text"
                        class="join_input en__field__input en__field__input--text" name="supporter.lastName"
                        value="">
                    </div>
                  </div>

                  <!-- email -->
                  <div class="en__field en__field--text en__field--306159 en__field--emailAddress en__mandatory">
                    <div class="join_inputen__field__element en__field__element--text">
                      <label for="en__field_supporter_emailAddress_inheader">E-mail Address (required)</label>
                      <input autocomplete="email" id="en__field_supporter_emailAddress_inheader" required
                        aria-required="true" type="text"
                        class="join_input en__field__input en__field__input--text"
                        name="supporter.emailAddress" value="">
                    </div>
                  </div>


                  <!-- opt in -->
                  <div
                    class="en__field en__field--checkbox en__field--question en__field--147505 en__field--opt-in">
                    <div class="en__field__element en__field__element--checkbox">
                      <div class="en__field__item">
                        <label for="en__field_supporter_questions_147505_inheader"
                          class="en__field__label en__field__label--item joinus-form--desc">
                          <input type="hidden" name="supporter.questions.147505"
                            class="en__field_supporter_questions_147505_control" value="N">
                          <input id="en__field_supporter_questions_147505_inheader" type="checkbox"
                            class="en__field__input en__field__input--checkbox">
                          I would like to receive email updates from Oxfam Canada. I understand I can
                          unsubscribe at any time.
                        </label>
                        <script>
                          document.getElementById('en__field_supporter_questions_147505_inheader')
                        </script>
                      </div>
                    </div>
                  </div>


                  <div class="en__submit">
                    <button id="joinus_form_submit_header"
                      class="joinus_form_submit header oxfam_button oxfam_orange_button">Sign Up</button>
                  </div>



                </form>
                <button id="joinus-close" class="joinus_close" aria-label="Close"><i class="fas fa-times"
                    aria-hidden="true"></i></button>

                <span class="modal-focus-trap" aria-hidden="true" id="joinus-bottom" tabindex="0"
                  data-target="search"></span>

              </div>
            </div>
          </div>
          <!-- SIGN UP FORM HEADER -->



          <!-- MAIN MENU -->
          <nav id="main-menu" aria-label="Site">
            <h2 id="nav-title" class="sr-only">Site Navigation</h2>
            <div class="menu-mobile-header">
              <a id="menu-40120-title-mobile" href="index.html"
                class="menu_main_logo menu-item menu-item-type-post_type menu-item-object-page menu-item-home current-menu-item page_item page-item-30765 current_page_item"
                title="">Oxfam Canada Home Page</a>
              <a class="menu_mobile_donate"
                href="#">Donate</a>
              <button class="mobile_menu_toggle" aria-expanded="false" aria-label="Navigation menu"><img
                  src="assets/images/menu-mobile-hamb.svg" alt="" aria-hidden="true"></button>
            </div>
            <h3 class="sr-only">Menu</h3>

            <ul class="menu-desktop" aria-labelledby="nav-title">
              <li>
                <a id="menu-41417-title" href="index.html" class="menu_main_logo menu-item menu-item-type-post_type menu-item-object-page" title="">
                  <span class="sr-only">Home Page</span>
                </a>
              </li>
              <li><a href="index.html" class="menu_main_mobile_shop menu-item"><button class="mainmenu_main">Home</button></a></li>
              <li><a href="#" class="menu_main_mobile_shop menu-item"><button class="mainmenu_main">About</button></a></li>
              <li><a href="#" class="menu_main_mobile_shop menu-item"><button class="mainmenu_main">Campaigns</button></a></li>
              <!-- <li><a href="#" class="menu_main_mobile_shop menu-item"><button class="mainmenu_main">Donate</button></a></li> -->
              <li><a href="#" class="menu_main_mobile_shop menu-item"><button class="mainmenu_main">Get Involved</button></a></li>
              <li><a href="#" class="menu_main_mobile_shop menu-item"><button class="mainmenu_main">Blog</button></a></li>
              <li><a href="#" class="menu_main_mobile_shop menu-item"><button class="mainmenu_main">Resources</button></a></li>
              <li><a href="#" class="menu_main_donate menu-itemoxfam_button oxfam_orange_button header-nav-donate" title="">Donate</a></li>

              <!-- <li data-id="menu-31-title">
                <button id="menu-31-title" aria-expanded="false"
                  class="mainmenu_main menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children">Who
                  We Are</button>
                <ul data-depth="0" class="sub-menu ">
                  <li data-id="menu-29971-title"><a id="menu-29971-title"
                      href="#"
                      class=" menu-item menu-item-type-post_type menu-item-object-page" title="">Our Story</a>
                  </li>
                  <li data-id="menu-30184-title"><a id="menu-30184-title"
                      href="#"
                      class=" menu-item menu-item-type-post_type menu-item-object-page" title="">Why Women’s
                      Rights</a></li>
                  <li data-id="menu-30218-title"><a id="menu-30218-title"
                      href="#"
                      class=" menu-item menu-item-type-post_type menu-item-object-page" title="">Our Mission,
                      Vision and Values</a></li>
                  <li data-id="menu-30219-title"><a id="menu-30219-title"
                      href="#"
                      class=" menu-item menu-item-type-post_type menu-item-object-page" title="">Finances and
                      Accountability</a></li>
                  <li data-id="menu-37721-title"><a id="menu-37721-title"
                      href="#"
                      class=" menu-item menu-item-type-post_type menu-item-object-landing-page" title="">How
                      Oxfam Canada Keeps People Safe</a></li>
                  <li data-id="menu-42284-title"><a id="menu-42284-title"
                      href="#"
                      class=" menu-item menu-item-type-custom menu-item-object-custom" title="">Our Work On
                      Anti-racism and Equity</a></li>
                  <li data-id="menu-41359-title"><a id="menu-41359-title"
                      href="#"
                      class=" menu-item menu-item-type-custom menu-item-object-custom" title="">Oxfam Canada
                      Complaints Policy</a></li>
                  <li data-id="menu-30055-title"><a id="menu-30055-title"
                      href="#"
                      class=" menu-item menu-item-type-post_type menu-item-object-page" title="">Our Team</a>
                  </li>
                  <li data-id="menu-30220-title"><a id="menu-30220-title"
                      href="#"
                      class=" menu-item menu-item-type-post_type menu-item-object-page" title="">Careers</a>
                  </li>
                  <li data-id="menu-40194-title"><a id="menu-40194-title"
                      href="#"
                      class=" menu-item menu-item-type-post_type menu-item-object-page" title="">Meet our
                      Fundraisers</a></li>
                  <li data-id="menu-30221-title"><a id="menu-30221-title"
                      href="#"
                      class=" menu-item menu-item-type-post_type menu-item-object-page" title="">Contact
                      Us</a></li>
                </ul>
              </li> -->
            </ul>
          </nav>
          <!-- MAIN MENU -->


        </header>
        <!--HEADER -->
        
        {children}

        <footer class="fl-page-footer-wrap" itemscope="itemscope" itemtype="https://schema.org/WPFooter">

          <h2 class="sr-only">Footer</h2>

          <div class="footer_wrapper">

            <!-- Footer Column 1 -->
            <div class="footer_col column1">

              <div class="h5 white">Lorem ipsum dolor sit amet consectetur.</div>

              <h3 id="footer-sn-title" class="sr-only">Connect with us</h3>
              <ul aria-labelledby="footer-sn-title" class="footer_sn_icons">
                <li>
                  <a href="#" target="_self" aria-label="Instagram">
                    <span class="ua-icon ua-icon-instagram-with-circle"></span>
                  </a>
                </li>
                <li>
                  <a href="#" target="_self" aria-label="Twitter">
                    <span class="ua-icon ua-icon-twitter-with-circle"></span>
                  </a>
                </li>
                <li>
                  <a href="#" target="_self" aria-label="Facebook">
                    <span class="ua-icon ua-icon-facebook-with-circle"></span>
                  </a>
                </li>
                <li>
                  <a href="#" target="_self" aria-label="Linkedin">
                    <span class="ua-icon ua-icon-linkedin-with-circle"></span>
                  </a>
                </li>
                <li>
                  <a href="#" target="_self" aria-label="Linkedin">
                    <span class="ua-icon ua-icon-linkedin-with-circle"></span>
                  </a>
                </li>
              </ul>

              <h3 id="footer-sn-contact" class="sr-only">Contact Us</h3>
              <div aria-labelledby="footer-sn-contact" class="footer_contact" role="region">
                <!-- <div><i class="ua-icon ua-icon-location-pin" aria-hidden="true"></i>39 McArthur Ave. Ottawa, Ontario, K1L 8L7</div> -->
                <div class="contact_item">
                  <i class="dashicons dashicons-before dashicons-email" aria-hidden="true"></i> 
                  <a href="mailto:info@gmail.com" data-enc-email="vasb[at]bksnz.pn" class="mail-link" data-wpel-link="ignore">info@gmail.com</a></div>
                <div class="contact_item">
                  <span class="los_icons ua-icon ua-icon-phone3" aria-hidden="true"></span>
                  <a href="tel:"><span class="sr-only">Phone:&nbsp;</span>+123456789</a>
                </div>
                <div class="contact_item">
                  <span class="los_icons ua-icon ua-icon-direction" aria-hidden="true"></span>
                  <a href="#">Lorem Acknowledgement</a>
                </div>
              </div>

            </div>
            <!-- Footer Column 1 -->
            <!-- Footer Column 2 -->
            <div class="footer_col column2">
              <h3 id="footer-useful-title" class="footer-nav-heading white">Useful links</h3>
              <ul aria-labelledby="footer-useful-title" class="footer_useful_links linostyle nomargin nopadding footer-nav-links">
                <li><a href="#" target="_self">Home</a></li>
                <li><a href="#" target="_self">About</a></li>
                <li><a href="#" target="_self">Campaigns</a></li>
                <li><a href="#" target="_self">Get Involved</a></li>
                <li><a href="#" target="_self">Blog</a></li>
                <li><a href="#" target="_self">Resources</a></li>
                <li><a href="#" target="_self">Contact</a></li>
              </ul>
              <ul aria-labelledby="footer-useful-title" class="footer_useful_links linostyle nomargin nopadding footer-nav-donate">
                <li><a href="#" target="_self" class="oxfam_orange_button oxfam_button footer_donate_button">Donate</a></li>
              </ul>
            </div>
            <!-- Footer Column 2 -->
            <!-- Footer Column 3 -->
            <div class="footer_col column3">
              <img class="oxfam_logo" src="assets/images/oxfamcanada_white.webp" aria-hiddeN="true" alt=""
                height="144" width="362">
              <div class="footer_member">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quam, incidunt!</div>
              <div class="logos_2col">
                <div class="col1">
                  A member of:
                  <a href="#"><img
                      src="assets/images/foot_logo_humcoa.png" alt="Humanitarian Coalition"></a>
                </div>
                <div class="col2">
                  <a href="#"><img src="assets/images/foot_logo_imagine.png" alt="Imagine Canada. Strong Charities. Strong Communities. Accredited since 2016"></a>
                </div>
              </div>
            </div>
            <!-- Footer Column 3 -->

          </div>

          <!-- Post footer -->
          <div class="postfooter">
            <div class="postfooter_inner">
              <div class="col1 footer_info">Charitable Reg/No. 42342423423</div>
              <div class="col2 footer_info">
                <h3 id="footer-legal-title" class="sr-only">Legal Links</h3>
                <ul aria-labelledby="footer-legal-title" class="nopadding nomargin">
                  <li class="footer_info_item"><a class="white" href="#">Privacy
                      Policy</a></li>
                  <li class="footer_info_item"><a class="white" href="#">Accessibility</a>
                  </li>
                  <li class="footer_info_item"><a class="white"
                      href="#">Careers</a></li>
                  <li class="footer_info_item"><a class="white"
                      href="#">About Us</a></li>
                </ul>
              </div>
              <div class="col3 footer_info">&copy; 2025 Wiselogix Technologies</div>
            </div>
          </div>

          <div class="footer_bottomline"></div>
          <!-- Post footer -->



        </footer>
        <div role="status" id="site-wide-aria-status" class="sr-only"></div>

        <!-- Scripts -->
        <script src="assets/js/dompurify.js"></script>
        <script src="assets/js/waypoints.js"></script>
        <script src="assets/js/fitvids.js"></script>
        <script src="assets/js/cookie-popup.js"></script>
        <script src="assets/js/iframe-master.js"></script>
        <script src="assets/js/thorttle-debounce.js"></script>
        <script src="assets/js/imagesLoaded.js"></script>
        <script src="assets/js/jquery-magnificpopup.js"></script>
        <script src="assets/js/bootstrap.js"></script>
        <script src="assets/js/bb-theme.js"></script>
      </body>
    </html>
  );
}
